spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${DATABASE_URI}

springdoc:
  packages-to-scan: com.neighborhoods
  # swagger-ui path
  swagger-ui:
    path: /api-docs

jwt:
  secret: ${JWT_SECRET}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: "*"

  metrics:
    export:
      prometheus:
        enabled: true