spring:
  data:
    mongodb:
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT:27017}
      database: neighborhoods
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      auto-index-creation: true
      authentication-database: admin

springdoc:
  packages-to-scan: com.neighborhoods
  # swagger-ui path
  swagger-ui:
    path: /api-docs

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: health, metrics, env