spring:
  data:
    mongodb:
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT:27017}
      database: neighborhoods
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      auto-index-creation: true
      authentication-database: admin

jwt:
  secret: ${JWT_SECRET}